### ISSUE TITLE
api.html is produced but empty

### ISSUE THREAD

**Issue by phun-ky** [punkave/grunt-dox#1]
I've got this in my gruntfile.js:

grunt.loadNpmTasks('grunt-dox');

dox: {
      files: {
        src: [tmpDir + '/js/*_/_.js'],
        dest: tmpDir + '/js/docs'
      }
    }

I see that the task is running and all the correct files are "doxxed" according to the log, but the api.html is empty.. I also see that grunt is exiting when the doxxing is complete. Maybe it's an error that's silent?

i use grunt@devel and node version 0.9.*

**Comment by codylindley** [comment]
I seem to have the same exact issue. grunt v0.3.17, node v0.8.11.

**Comment by phun-ky** [comment]
A wild guess is that dox has moved to not parse HTML as output anymore, just a JSON object: "Dox no longer generates an opinionated structure or style for your docs, it simply gives you a JSON representation, allowing you to use markdown and JSDoc-style tags."

**Comment by codylindley** [comment]
I believe that has been what it always does. That is why this uses https://github.com/punkave/dox-foundation

**Comment by phun-ky** [comment]
Dox-foundation use Dox.. "Use dox to automatically generate beautiful html documentation." And I see in the dox-foundation code that it calles dox's method parseComments, which in return does not return HTML (At least what I read from the documentation)

**Comment by stephenmathieson** [comment]
Any update @punkave ?

**Comment by atesgoral** [comment]
@phun-ky Are you on Windows? I had the same issue on Windows. It's because the current grunt script assumes `cat` to be there (i.e. isn't tuned for Windows yet).

**Comment by codylindley** [comment]
I'm on osx.

**Comment by atesgoral** [comment]
The grunt script currently doesn't log any errors when something goes bad. To figure out what's going on, try locally editing node_modules/grunt-dox/tasks/dox.js to add error logging in the `exec` callback:

```
if (!error) done();
if (error) grunt.log.writeln("ERROR "+ error);
```

**Comment by mattmcmanus** [comment]
@codylindley, were you able to try @atesgoral test?

Sorry for the delay in getting back to you all. I haven't had much time to work on this code. Dox-foundation has changed a lot since the last update of this. I just pushed 0.2.1 which specifies the older version of dox-foundation. This should hopefully fix the problem. Let me know how it goes.

**Comment by phun-ky** [comment]
@atesgoral Sorry for the late response here, yes I am on windows, but i use mSysGit aswell, so I have the `cat` command available. I'm getting this error:

``` bash
ERROR Error: Command failed: dox-foundation ...
```

Basically, dox-foundation is not installed globally/is not found. Will try to circumvent this, maybe fork this project and fix this, stay tuned.

Update:

It seems that the way `dox-foundation` is called with this code:

``` javascript
exec('cat ' + files.join(' ') + ' | dox-foundation', function(error, stout, sterr){
      grunt.file.write(dest + '/' + 'api.html', stout);
      grunt.log.writeln('Files "' + files.join(' ') + '" doxxed.');
      done(error);
    })
```

expects that `dox-foundation` is installed globally. I'm currently trying to figure out how to call this locally with `node_modules/.bin/dox-foundation` , specifically I'm trying to figure out how to send the String content of `files.join(' ')` to `dox-foundation` like this:

``` javascript
grunt.registerMultiTask('dox', 'Generate dox output ', function() {

    var files = grunt.file.expandFiles(this.file.src),
        dest = this.file.dest;
        done = this.async(),
        doxCmd = '';

    // Cleanup any existing docs
    rimraf.sync(dest);

    if(process.platform == 'win32'){

      doxCmd = '"node_modules' + path.sep + '.bin' + path.sep + 'dox-foundation" "' + files.join(' ') + '" -d';
    } else {

      doxCmd = 'cat ' + files.join(' ') + ' |' + 'node_modules' + path.sep + '.bin' + path.sep + 'dox-foundation';
    }

    exec(doxCmd, function(error, stout, sterr){
      grunt.file.write(dest + '/' + 'api.html', stout);
      grunt.log.writeln('Files \n"' + files.join('\n') + '" doxxed.');
      if (!error) done();
      if (error) grunt.log.writeln("ERROR "+ error);

    })
  });
```

**Comment by phun-ky** [comment]
I fixed it for now, needs a bit more tweaking ( `type` for windows ), see  #4 for code/pull request. Close issue if you consider my fix to be accepted. ( Fell free to update package.json with me as contributor if you bother with it )

**Comment by israels** [comment]
You need to publish latest to NPM.  0.2.2 does not include the fixes for Windows.

**Comment by mattmcmanus** [comment]
Sorry! I haven't been able to give this project the time it deserves. I just pushed 0.3 which works with dox-foundation 0.4
