### ISSUE TITLE
Unable to pass multiple words to title

### ISSUE THREAD

**Issue by benbarnett** [punkave/grunt-dox#12]
If I pass:

``` json
dox: {
      options: {
        title: 'This is a great title'
      },
      files: {
        src: ['modules', 'routes'],
        dest: 'docs'
      }    
    }
```

The output is just 'This'

**Comment by mattmcmanus** [comment]
This is great @benbarnett! Thanks for catching that. Could you do me a favor and update your pull request to include an ignore example to the readme?

**Comment by benbarnett** [comment]
Cheers @mattmcmanus. No worries - example added.

**Comment by mattmcmanus** [comment]
You sir are a gentleman and a scholar! `0.4.2` has been published
