### ISSUE TITLE
grunt-dox task fails with ENOENT error sourcing from _head.jade, line 8

### ISSUE THREAD

**Issue by okfro** [punkave/grunt-dox#15]
Just as with issue #14, I've been trying to autogenerate API documentation for my project, [OJ](https://github.com/somecallmechief/oj). I'm stuck behind bugs in grunt-jsdoc and grunt-jsduck, and I found dox and thus grunt-dox by proxy.

I used the same configuration as in the readme, but I get an exception every time, full text here: https://gist.github.com/somecallmechief/31c272bc0d6ae554202a.

> > ERROR:  Error: Command failed: C:\Users\Froehlich\Documents\GitHub\oj\node_mo
> > dules\grunt-dox\node_modules\dox-foundation\views_head.jade, line 8:
> > 
> > fs.js:427
> >   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode)

I get a similar error when trying to use dox-foundation; but when I call dox directly I get a JSON file that looks correct.

**Comment by mattmcmanus** [comment]
Hey @somecallmechief, I'm looking into this. I believe this is definitely an issue with dox-foundation and not grunt-dox. I'll close this out when I figure something out

**Comment by mattmcmanus** [comment]
Could you give me an example of the dox-foundation command that you ran? I'm having trouble reproducing the error

**Comment by mattmcmanus** [comment]
Alrighty, I pulled down your repo and play around for a while. I made some changes that appear to have worked. I'm pushing dox-foundation `v0.4.9` right now. 

I'm not sure dox-foundation will be the right tool though! There are some serious contraints on the template that seem to fail when you get to a project as large as yours. I'm happy to take suggestions and even more so to accept pull requests!

**Comment by okfro** [comment]
@mattmcmanus Thanks for looking into it! I'll give it another whirl tomorrow and see how far I get.

[Update]

That indeed fixes the error I reported, and I do now understand your comment. Given the current template, you do start to see the constraints when using a project like mine. Still, thanks for your help.
