### ISSUE TITLE
Newlines inside paragraphs are converted to <br>

### ISSUE THREAD

**Issue by roessland** [punkave/grunt-dox#18]
This doc string

``` markdown
/**
* Title
*
* All methods return a [jQuery Deferred Object](http://api.jquery.com/category/deferred-object/>) 
* which can be chained.
*/
```

Ends up as this HTML with, with newlines converted to `<br>`:

``` html
<p>
    All methods return a <a href="http://api.jquery.com/category/deferredobject/">jQuery Deferred Object</a> 
    <br>
    which can be chained.
</p>
```

When using a list, newlines are ignored as usual:

``` markdown
*    
* - Enable caching using offline storage, so things are fast when you reopen
*   the app. [jQuery Offline](https://github.com/wycats/jquery-offline)
*   provides `$.retrieveJSON` which is a HTML5 localStorage cached version
*   of `$.getJSON`.
*
```

``` html
<li>Enable caching using offline storage, so things are fast when you reopen
the app. <a href="https://github.com/wycats/jquery-offline">jQuery Offline</a>
provides <code>$.retrieveJSON</code> which is a HTML5 localStorage cached 
version of <code>$.getJSON</code>.</li>
```

Is this a bug, or is there a way to ignore newlines in text paragraphs? Thanks.

**Comment by mattmcmanus** [comment]
I wish there was! That particular content is generated by [dox](https://github.com/visionmedia/dox). I'm just throwing it into a template.

If anything, this should be a issue under [dox-foundation](https://github.com/punkave/dox-foundation), the library I use to make the html. I've thought about hacking together a bit of JS that would remove all `<br />`s. Feel free to send a pull request there if you do it!
