### ISSUE TITLE
jade tmpl out of date

### ISSUE THREAD

**Issue by japrescott** [punkave/grunt-dox#19]
/jade/lib/runtime.js:200

> >   throw err;
> >         ^
> > Error: /node_modules/grunt-dox/node_modules/dox-foundation/views/template.jade:73
> >     71| 
> >     72|     include ./_footer.jade
> > 
> > > 73| 
> > 
> > `doctype 5` is deprecated, you must now use `doctype html`

**Comment by mattmcmanus** [comment]
I just updated the release of `dox-foundation` which was the source of this error. Make sure you using at least `0.5.5` of `dox-foundation`
