### ISSUE TITLE
Request: Add options

### ISSUE THREAD

**Issue by phun-ky** [punkave/grunt-dox#3]
Currently, grunt-dox does not support to pass options to dox-foundation. 

For example, the option to add a custom documentation title would be handy :)

**Comment by mattmcmanus** [comment]
This is definitely on my list. I've been focusing on dox-foundation and haven't given this module much love. I'll try to get to it soon.

**Comment by mattmcmanus** [comment]
Hey @phun-ky 

Thank you for all the amazing work you've been doing on these projects. I just merged in your pull request and it looks like you already took care of this. I'll update the documentation and publish this version ASAP

**Comment by phun-ky** [comment]
Thanks for the implementation of my PR! Keep up the good work!!
