### ISSUE TITLE
Add support for files with absolute paths, '.' is sent to dox-foundation

### ISSUE THREAD

**Issue by phun-ky** [punkave/grunt-dox#7]
I'm wrapping grunt with some other software, and this requires all filepaths to be either relative to the app path (not project path) or absolute.

**Grunt normally would reside in this directory**

```
C:\Users\Workspace\MyProject\ >
```

**But since we wrap grunt in an app, Grunt resides here**

```
C:\Users\Workspace\MyProject\ > cd ..\<my app>
C:\User\Workspace\<my app>\ >
```

**This means that all files sent to `grunt-dox` looks like this:**

```
dox: {
  files: {
    src: ['../MyProject/js/src/**/*.js'],
    dest: '../MyProject/js/docs'
  }
},
```

**And the result sent to dox-foundation looks like this:**

```
C:\Users\QE1\Workspace\app>node_modules\grunt-dox\node_modules\.bin\dox-foundation --source . --target C:\Users\QE1\Workspace\company\fpi_client\js\docs\ --title "Client"
```

With your latest rewrite, grunt-dox now takes one directory and parses with no subdirectories. The files generated looks a whole lot better when doing it like this, but no support for sub-dirs.

If I try to rewrite grunt-dox to use the old method using stdio, the result is not satisfying.

I know that this is not your top priority, but would be nice to add support for. Maybe this should be a discussion regarding both grunt-dox and dox-foundation, on what it should accept..

Reported a relevant issue here: https://github.com/punkave/dox-foundation/issues/21

**Comment by mattmcmanus** [comment]
I pushed 0.3.1 which resolves the path before it passes it along to dox-foundation. Let me know if that works for you. I'll comment on the other issues accordingly. 

Thanks again for all the attention and help

**Comment by phun-ky** [comment]
Sorry for the long delay with my response, but it has been hectic. We had less focus on the dox generation in our build system, but will try to focus on testing and checking if everything works ok ;) Thanks for the feedback!
